Did task 78
clonediff/.NETflix pull request #46
Opened 2023-10-28 09:13 UTC by Ilfatt

2023-10-28 10:02 UTC, NailZinn requested changes

2023-10-28 10:02 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Enums/GetAllEnums/GetAllEnumsQueryHandler.cs
> +public class GetAllEnumsQueryHandler
Сделай хэндлер internal

2023-10-28 14:27 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Enums/GetAllEnums/GetAllEnumsQueryHandler.cs
> +public class GetAllEnumsQueryHandler
Сделал

2023-10-28 17:56 UTC, NailZinn requested changes

2023-10-28 17:56 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Enums/Queries/GetAllEnums/GetAllEnumsQueryHandler.cs
> +            .ToListAsync(cancellationToken);
Лучше сразу await писать. У меня этот код упал из-за конкурентного доступа к контексту, так как эти таски запускаются параллельно, а контекст не потокобезопасный

2023-10-28 18:08 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Enums/Queries/GetAllEnums/GetAllEnumsQueryHandler.cs
> +            .ToListAsync(cancellationToken);
Я привык контекст регать как transient , забыл посмотреть как он у вас зареган;

2023-10-28 18:12 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Enums/Queries/GetAllEnums/GetAllEnumsQueryHandler.cs
> +            .ToListAsync(cancellationToken);
исправил

2023-10-28 20:33 UTC, NailZinn approved these changes

2023-10-29 08:16 UTC, clonediff approved these changes

2023-10-29 08:46 UTC, merged