Netflix 79
clonediff/.NETflix pull request #47
Opened 2023-10-28 10:35 UTC by Ilfatt

2023-10-28 18:24 UTC, NailZinn requested changes

2023-10-28 18:24 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Persons/Shared/PersonDto.cs
PersonDto можно перенести в папку GetAll, так как он больше нигде не используется

2023-10-28 20:30 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Persons/Shared/PersonDto.cs
Сделал

2023-10-28 20:46 UTC, NailZinn approved these changes

2023-10-29 08:19 UTC, clonediff approved these changes

2023-10-29 09:01 UTC, merged