NETFLIX-82
clonediff/.NETflix pull request #48
Opened 2023-10-28 14:27 UTC by Ilfatt

Задание звучало как : Переписать текущий UserService на

3 commands: SetRole, BanUser, UnbanUser
4 queries: GetUsersCount, GetAllRoles, GetUsersFiltered, GetEmail
Все маппинги и dto перенести в application layer в соответствующие папки.
Заменить выброс исключений на возврат Result<TSuccess, TFailure>.
Дублирующуюся валидацию вынести в behaviors.

Но GetEmail не нужен так как он используется только внутри этих кверей где уже есть email пользователя, а запроса для получения почты в контроллере нет

2023-10-28 18:56 UTC, NailZinn requested changes

2023-10-28 18:56 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Admin.Application/ApplicationServicesRegistration.cs
>          serviceCollection.AddMediatR(config => config.RegisterServicesFromAssembly(Assembly.GetExecutingAssembly()));
Можно сразу использовать static поле Assembly

2023-10-28 20:36 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/ApplicationServicesRegistration.cs
>          serviceCollection.AddMediatR(config => config.RegisterServicesFromAssembly(Assembly.GetExecutingAssembly()));
Я исправил, но на всякий случай скажу, это был не мой код

2023-10-28 20:48 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Admin.Application/ApplicationServicesRegistration.cs
>          serviceCollection.AddMediatR(config => config.RegisterServicesFromAssembly(Assembly.GetExecutingAssembly()));
В другой ветке аналогичный момент тоже пофиксили

2023-10-28 20:48 UTC, NailZinn approved these changes

2023-10-29 08:50 UTC, clonediff requested changes

2023-10-29 08:50 UTC, clonediff commented on DotNetflixServer/DotNetflix.Admin.Application/Behaviors/UserIdValidationBehavior.cs
> +            .AnyAsync(x => x.Id == request.UserId, cancellationToken);
Не лучше будет использовать UserManager? Аналогичный вопрос и в других методах

2023-10-29 09:22 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/Behaviors/UserIdValidationBehavior.cs
> +            .AnyAsync(x => x.Id == request.UserId, cancellationToken);
Заменил

2023-10-29 09:48 UTC, NailZinn requested changes

2023-10-29 09:48 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Users/Commands/BanUser/BanUserCommandHandler.cs
> +        var user = await _userManager.Users
Тут можно использовать `FindByIdAsync()`

2023-10-29 10:44 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Admin.Application/Features/Users/Commands/BanUser/BanUserCommandHandler.cs
> +        var user = await _userManager.Users
ага, все

2023-10-29 10:52 UTC, NailZinn approved these changes

2023-10-29 11:39 UTC, clonediff approved these changes

2023-10-29 11:50 UTC, merged