NETFLIX-71
clonediff/.NETflix pull request #50
Opened 2023-10-28 19:36 UTC by Zancrow20

2023-10-28 20:12 UTC, NailZinn requested changes

2023-10-28 20:12 UTC, NailZinn commented on DotNetflixServer/Contracts/Forms/LoginForm.cs
Перенеси в папку Login и убери атрибут

2023-10-28 20:12 UTC, NailZinn commented on DotNetflixServer/Contracts/Forms/RegisterForm.cs
Перенеси в папку Register и убери атрибут

2023-10-28 20:12 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/ApplicationServicesRegistration.cs
> +                    ValidationBehavior<RegistrationCommand, string>>();
Попробуй зарегать behaviors через RegisterBehavior

2023-10-28 20:28 UTC, NailZinn requested changes

2023-10-28 20:28 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Behaviors/ValidationBehavior.cs
> +public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, Result<TResponse, IEnumerable<string>>>
Возможно, лучше возвращать просто string, чтобы не плодить массивы из одного элемента в хэндлерах

2023-10-29 12:30 UTC, Zancrow20 commented on DotNetflixServer/Contracts/Forms/LoginForm.cs
Перенес

2023-10-29 12:30 UTC, Zancrow20 commented on DotNetflixServer/Contracts/Forms/RegisterForm.cs
Перенес и убрал все атрибуты

2023-10-29 12:32 UTC, Zancrow20 commented on DotNetflixServer/DotNetflix.Application/ApplicationServicesRegistration.cs
> +                    ValidationBehavior<RegistrationCommand, string>>();
Зарегистрировал через RegisterBehaviorReturningResult, но убрать третий аргумент не получается. У ValidationBehavior поменял notnull на IRequest<Result<TResponse, string>>

2023-10-29 12:33 UTC, Zancrow20 commented on DotNetflixServer/DotNetflix.Application/Behaviors/ValidationBehavior.cs
> +public class ValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, Result<TResponse, IEnumerable<string>>>
Вернул string

2023-10-29 12:43 UTC, NailZinn requested changes

2023-10-29 12:43 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Behaviors/ValidationBehavior.cs
> +    where TRequest : IRequest<Result<TResponse,string>>
До этого правильно было

2023-10-29 13:27 UTC, NailZinn requested changes

2023-10-29 13:27 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Features/Authentication/Commands/Login/LoginForm.cs
> +    public bool Remember { get; set; } = default!;
Убери default!

2023-10-29 13:27 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Features/Authentication/Commands/Register/RegisterForm.cs
> +    public DateTime Birthday { get; set; } = default!;
Убери default!

2023-10-29 18:36 UTC, NailZinn approved these changes

2023-10-29 18:36 UTC, merged