did task-90
clonediff/.NETflix pull request #61
Opened 2023-12-02 12:54 UTC by Ilfatt

2023-12-03 11:37 UTC, NailZinn requested changes

2023-12-03 11:37 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Storage/Services/TemporaryStorageMetadata/RedisStorageService.cs
Я думаю, что можно убрать async/await везде в качестве оптимизации

2023-12-03 14:32 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Storage/Services/TemporaryStorageMetadata/RedisStorageService.cs
+ async await имеет hot path оптимизацию

2023-12-03 14:35 UTC, NailZinn approved these changes

2023-12-04 14:59 UTC, clonediff approved these changes

2023-12-04 15:00 UTC, merged