Netflix 99
clonediff/.NETflix pull request #71
Opened 2024-03-23 18:58 UTC by Ilfatt

2024-03-23 19:30 UTC, NailZinn requested changes

2024-03-23 19:30 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Features/Subscriptions/Commands/ExtendSubscription/ExtendSubscriptionCommandHandler.cs
> +            throw;
Замени пж пробрасывание исключения на возврат строки - у нас исключения не отлавливаются, всё на Result построено

2024-03-23 19:30 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Features/Subscriptions/Commands/PurchaseSubscription/PurchaseSubscriptionCommandHandler.cs
> +            throw;
Тут тоже

2024-03-23 19:30 UTC, NailZinn commented on DotNetflixServer/DotNetflix.Application/Features/Subscriptions/Commands/PurchaseSubscription/PurchaseSubscriptionCommandHandler.cs
> +            _paymentServiceClient.RefundAsync(cardData, cancellationToken: cancellationToken);
Тут await надо? В другом хэндлере он есть, а здесь нет

2024-03-23 19:34 UTC, Ilfatt commented on DotNetflixServer/DotNetflix.Application/Features/Subscriptions/Commands/PurchaseSubscription/PurchaseSubscriptionCommandHandler.cs
> +            throw;
тут все верно

2024-03-24 11:05 UTC, NailZinn approved these changes

2024-03-24 13:13 UTC, merged